paths:
  - django_api_example
exclude: .*/test
skip_magic: True
skip_file_doc: True
skip_init: True
skip_class_def: True
skip_private: True
follow_links: True
accept_empty: True
ignore_names_file: .*/test
fail_under: 90
percentage_only: True
ignore_patterns: # Dict with key/value pairs of file-pattern/node-pattern
  .*:
    - "__.+__" # ignore special methods
